// Every word harogatOS shows, in English and Spanish. The page's <html lang> picks one. Capitals
// inside the screen are how old terminals talked; the case's buttons are sentence case like the
// rest of the site.

const en = {
  // The case
  tabs: { stacker: "Stacker", hiscores: "Scores", faces: "Draw", gallery: "Gallery", picross: "Picross" },
  shutDown: "Shut down",
  previousPage: "Previous page",
  nextPage: "Next page",

  // Stacker
  noSignal: "NO SIGNAL",
  scoreboardHome: "the scoreboard lives on fharo.dev",
  nobodyYet: "NOBODY YET",
  topSpotYours: "the top spot is yours",
  who: "WHO",
  scoreCol: "SCORE",
  rowsCol: "ROWS",
  bestStackers: "BEST STACKERS",
  loading: "LOADING...",
  signYourScore: "SIGN YOUR SCORE",
  pickOtherLetters: "PICK SOME OTHER LETTERS",
  save: "SAVE",
  skip: "SKIP",
  letterUp: (i: number) => `Letter ${i} up`,
  letterDown: (i: number) => `Letter ${i} down`,
  letter: (i: number, l: string) => `Letter ${i}: ${l}`,
  ready: "READY",
  youMadeIt: "YOU MADE IT!",
  gameOver: "GAME OVER",
  perfect: "PERFECT!",
  blocksLeft: (n: number) => `${n} BLOCK${n > 1 ? "S" : ""} LEFT`,
  max: (n: number) => `MAX ${n}`,
  stackerHow: "Stop each row on top of the last. Whatever hangs over the edge falls off.",
  pressSpaceOrTap: "PRESS SPACE OR TAP",
  pointsAndRows: (points: string, rows: number) => `${points} POINTS · ${rows} ROWS`,
  saving: "SAVING...",
  youPlaced: (rank: number) => `YOU PLACED #${rank}`,
  points: (points: string) => `${points} POINTS`,
  notSaved: "NO SIGNAL. THIS ONE WASN'T SAVED.",
  onlyOnSite: "SCORES ONLY SAVE ON FHARO.DEV",
  tapToPlayAgain: "TAP TO PLAY AGAIN",
  spaceToPlayAgain: "SPACE TO PLAY AGAIN",
  score: "SCORE",
  row: "ROW",
  best: "BEST",
  topOfStack: "TOP OF THE STACK",
  missed: "THAT ONE MISSED",
  spaceOrTapToStop: "SPACE OR TAP TO STOP",

  // Faces
  tools: { pen: "PEN", blush: "BLUSH", erase: "ERASE" },
  mirror: (on: boolean) => `MIRROR ${on ? "ON" : "OFF"}`,
  phosphor: { green: "Green", amber: "Amber", blue: "Blue", pink: "Pink" },
  clear: "CLEAR",
  signIt: "SIGN IT >",
  drawingGrid: "Drawing grid. Arrow keys move the cursor, space paints a cell, enter signs it.",
  yourName: "YOUR NAME",
  whoDrewThis: "who drew this",
  aNote: "A NOTE",
  optional: "optional",
  goesOnYourPc: "Your face goes on your PC right away. Everyone else sees it once it's approved.",
  back: "< BACK",
  sending: "SENDING...",
  send: "SEND",
  sent: "SENT!",
  onYourPc: "It's on your PC until you click the PC. Everyone else sees it once it's approved.",
  drawAnother: "DRAW ANOTHER",
  seeItOnPc: "SEE IT ON THE PC",
  galleryHome: "the gallery lives on fharo.dev",
  noFacesYet: "NO FACES YET",
  drawTheFirst: "draw the first one",
  noNote: "(no note)",
  showOnPc: "SHOW ON PC",
  errors: {
    "slow-down": "THAT'S A LOT OF FACES. TRY AGAIN IN AN HOUR.",
    offline: "NO SIGNAL. YOUR DRAWING IS SAVED, TRY AGAIN LATER.",
    author: "SIGN WITH A NAME, UP TO 20 CHARACTERS.",
    message: "KEEP THE NOTE UNDER 80 CHARACTERS.",
    art: "DRAW A LITTLE MORE FIRST.",
    bot: "COULDN'T CHECK THIS IS A PERSON. TRY AGAIN.",
    "queue-full": "THE QUEUE IS FULL RIGHT NOW. TRY AGAIN LATER.",
  } as Record<string, string>,
  somethingWrong: "SOMETHING WENT WRONG. TRY AGAIN.",

  // Picross
  picrossGrid: "Picross grid. Arrow keys move, space fills a cell, X crosses it out.",
  fill: "FILL",
  cross: "CROSS",
  puzzles: "PUZZLES",
  solvedIn: (time: string) => `SOLVED IN ${time}`,
  faceByName: (name: string) => `face by ${name}`,
  pcFace: (name: string) => `HARO-PC's ${name} face`,
  nextPuzzle: "NEXT",
  solvedCount: (done: number, total: number) => `${done}/${total} SOLVED`,
  noVisitorPuzzles: "visitor faces load on fharo.dev",
  faceNames: ["Normal", "Happy", "Surprised", "Wink", "Love", "Sleepy", "Excited", "Cool"],
  levels: { easy: "EASY", medium: "MEDIUM", hard: "HARD" },
};

export type Strings = typeof en;

const es: Strings = {
  tabs: { stacker: "Stacker", hiscores: "Récords", faces: "Dibujar", gallery: "Galería", picross: "Picross" },
  shutDown: "Apagar",
  previousPage: "Página anterior",
  nextPage: "Página siguiente",

  noSignal: "SIN SEÑAL",
  scoreboardHome: "el marcador vive en fharo.dev",
  nobodyYet: "NADIE AÚN",
  topSpotYours: "el primer lugar es tuyo",
  who: "QUIÉN",
  scoreCol: "PUNTOS",
  rowsCol: "FILAS",
  bestStackers: "RÉCORDS",
  loading: "CARGANDO...",
  signYourScore: "FIRMA TU PUNTAJE",
  pickOtherLetters: "ESCOGE OTRAS LETRAS",
  save: "GUARDAR",
  skip: "SALTAR",
  letterUp: (i) => `Letra ${i} arriba`,
  letterDown: (i) => `Letra ${i} abajo`,
  letter: (i, l) => `Letra ${i}: ${l}`,
  ready: "LISTO",
  youMadeIt: "¡LO LOGRASTE!",
  gameOver: "FIN DEL JUEGO",
  perfect: "¡PERFECTO!",
  blocksLeft: (n) => (n > 1 ? `QUEDAN ${n} BLOQUES` : `QUEDA ${n} BLOQUE`),
  max: (n) => `MÁX ${n}`,
  stackerHow: "Detén cada fila sobre la anterior. Lo que sobresalga se cae.",
  pressSpaceOrTap: "PRESIONA ESPACIO O TOCA",
  pointsAndRows: (points, rows) => `${points} PUNTOS · ${rows} FILAS`,
  saving: "GUARDANDO...",
  youPlaced: (rank) => `QUEDASTE #${rank}`,
  points: (points) => `${points} PUNTOS`,
  notSaved: "SIN SEÑAL. ESTE NO SE GUARDÓ.",
  onlyOnSite: "LOS PUNTAJES SOLO SE GUARDAN EN FHARO.DEV",
  tapToPlayAgain: "TOCA PARA JUGAR DE NUEVO",
  spaceToPlayAgain: "ESPACIO PARA JUGAR DE NUEVO",
  score: "PUNTOS",
  row: "FILA",
  best: "MEJOR",
  topOfStack: "¡HASTA ARRIBA!",
  missed: "ESA NO ENTRÓ",
  spaceOrTapToStop: "ESPACIO O TOCA PARA PARAR",

  tools: { pen: "LÁPIZ", blush: "RUBOR", erase: "BORRAR" },
  mirror: (on) => `ESPEJO ${on ? "SÍ" : "NO"}`,
  phosphor: { green: "Verde", amber: "Ámbar", blue: "Azul", pink: "Rosa" },
  clear: "LIMPIAR",
  signIt: "FIRMAR >",
  drawingGrid: "Cuadrícula de dibujo. Las flechas mueven el cursor, espacio pinta una celda, enter la firma.",
  yourName: "TU NOMBRE",
  whoDrewThis: "quién la dibujó",
  aNote: "UNA NOTA",
  optional: "opcional",
  goesOnYourPc: "Tu cara aparece en tu PC de inmediato. Los demás la ven cuando se apruebe.",
  back: "< ATRÁS",
  sending: "ENVIANDO...",
  send: "ENVIAR",
  sent: "¡ENVIADA!",
  onYourPc: "Está en tu PC hasta que le des clic. Los demás la ven cuando se apruebe.",
  drawAnother: "DIBUJAR OTRA",
  seeItOnPc: "VERLA EN LA PC",
  galleryHome: "la galería vive en fharo.dev",
  noFacesYet: "AÚN NO HAY CARAS",
  drawTheFirst: "dibuja la primera",
  noNote: "(sin nota)",
  showOnPc: "MOSTRAR EN PC",
  errors: {
    "slow-down": "SON MUCHAS CARAS. INTENTA DE NUEVO EN UNA HORA.",
    offline: "SIN SEÑAL. TU DIBUJO ESTÁ GUARDADO, INTENTA MÁS TARDE.",
    author: "FIRMA CON UN NOMBRE DE HASTA 20 CARACTERES.",
    message: "LA NOTA DEBE TENER MENOS DE 80 CARACTERES.",
    art: "DIBUJA UN POCO MÁS PRIMERO.",
    bot: "NO PUDIMOS COMPROBAR QUE ERES PERSONA. INTENTA DE NUEVO.",
    "queue-full": "LA FILA ESTÁ LLENA AHORA. INTENTA MÁS TARDE.",
  },
  somethingWrong: "ALGO SALIÓ MAL. INTENTA DE NUEVO.",

  picrossGrid: "Cuadrícula de picross. Las flechas mueven, espacio rellena una celda, X la tacha.",
  fill: "RELLENAR",
  cross: "TACHAR",
  puzzles: "PUZZLES",
  solvedIn: (time) => `RESUELTO EN ${time}`,
  faceByName: (name) => `cara de ${name}`,
  pcFace: (name) => `la cara ${name} de HARO-PC`,
  nextPuzzle: "SIGUIENTE",
  solvedCount: (done, total) => `${done}/${total} RESUELTOS`,
  noVisitorPuzzles: "las caras de visitantes cargan en fharo.dev",
  faceNames: ["normal", "feliz", "sorprendida", "guiño", "enamorada", "dormida", "emocionada", "cool"],
  levels: { easy: "FÁCIL", medium: "MEDIO", hard: "DIFÍCIL" },
};

/** The strings for the page's language. The language never changes while a page is open. */
export const strings = (): Strings => (typeof document !== "undefined" && document.documentElement.lang === "es" ? es : en);
